#!/bin/bash

sh -c "$(curl -fsLS get.chezmoi.io)"
sudo mv ./bin/chezmoi /usr/local/bin/chezmoi
rm -rf ./bin

if command -v chezmoi >/dev/null 2>&1; then
	echo "==> chezmoi was downloaded successfully"
else
	echo "==> there was an error running chezmoi.."
	exit 1
fi

chezmoi init --verbose --recurse-submodules=false https://github.com/josemiguelo/.dotfiles.git

sleep 3
chezmoi apply

init_bootstrap_file="$HOME/.local/share/bootstrap/init.sh"
chmod +x $init_bootstrap_file
. $init_bootstrap_file
