#! /bin/env bash

#TODO: make this idempotent

sudo apt update
apt_install bash

git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git
make -C ble.sh install PREFIX=~/.local
rm -rf ./ble.sh
