name: loadout
root: ~/Repos/gh/josemiguelo/loadout

windows:
  - agent: claude --continue
  - loadout:
  - dotfiles:
      root: ~/.local/share/chezmoi
  - wiki:
      root: ~/Repos/gh/josemiguelo/loadout.wiki/all_worktrees/master
