return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    opts = {
      highlights = {
        CursorLineNr = { fg = "${purple}" },
        LineNrAbove = { fg = "${blue}" },
        LineNrBelow = { fg = "${blue}" },
        CursorColumn = { bg = "${cursorline}" },
        WinSeparator = { fg = "${blue}" },
        SnacksPicker = { bg = "NONE" },
        SnacksPickerBorder = { bg = "NONE" },
        Normal = { bg = "NONE" },
        NormalFloat = { bg = "NONE" },
        SnacksTerminal = { bg = "NONE" },
      },
      options = {
        transparency = true,
        terminal_colors = true,
        lualine_transparency = true,
        highlight_inactive_windows = true,
      },
      styles = {
        types = "bold",
        methods = "bold",
        numbers = "NONE",
        strings = "NONE",
        comments = "italic",
        keywords = "bold,italic",
        constants = "bold",
        functions = "italic",
        operators = "NONE",
        variables = "NONE",
        parameters = "italic",
        conditionals = "bold,italic",
        virtual_text = "italic",
      },
    },
  },
  { "LazyVim/LazyVim", opts = { colorscheme = "vaporwave" } },
  { "catppuccin/nvim", cond = false },
  { "folke/tokyonight.nvim", cond = false },
}
