#! /bin/env bash

#TODO: make this idempotent

step "installing docker..."
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
	"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
 "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |
	sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo apt update
apt_install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

step "configuring docker groups..."
group=docker
grep -qw ^$group /etc/group || sudo groupadd $group
sudo usermod -aG $group $USER
[[ -f /var/run/docker.sock ]] && sudo chmod 666 /var/run/docker.sock

step "configuring docker-compose..."
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
