#! /bin/env bash

#TODO: make this idempotent

sudo add-apt-repository multiverse
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true |
	sudo debconf-set-selections
sudo apt-get install ttf-mscorefonts-installer -y
