#! /bin/env bash

#TODO: make this idempotent

apt_install ffmpeg libsdl2-2.0-0 adb \
	pkg-config meson ninja-build libsdl2-dev \
	libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
	libswresample-dev libusb-1.0-0 libusb-1.0-0-dev

#TODO: try to not use this
git clone https://github.com/Genymobile/scrcpy
cd scrcpy
./install_release.sh
cd ..
rm -rf scrcpy
