#! /bin/env bash

sudo apt install -y \
	'bsdutils' \
	'cmake' \
	'dpkg-dev' \
	'fakeroot' \
	'gcc' \
	'g++' \
	'libegl1-mesa-dev' \
	'libssl-dev' \
	'libfontconfig1-dev' \
	'libwayland-dev' \
	'libx11-xcb-dev' \
	'libxcb-ewmh-dev' \
	'libxcb-icccm4-dev' \
	'libxcb-image0-dev' \
	'libxcb-keysyms1-dev' \
	'libxcb-randr0-dev' \
	'libxcb-render0-dev' \
	'libxcb-xkb-dev' \
	'libxkbcommon-dev' \
	'libxkbcommon-x11-dev' \
	'libxcb-util-dev' \
	'lsb-release' \
	'xdg-utils' \
	'xorg-dev'

cd /tmp

#TODO:replace with wez/wezterm.git once the PR has been approved
git clone --depth=1 --branch=deploy-popos --recursive https://github.com/josemiguelo/wezterm.git
cd wezterm

git submodule update --init --recursive
cargo build --release

sudo ci/deploy.sh
TAG_NAME=${TAG_NAME:-$(git -c "core.abbrev=8" show -s "--format=%cd-%h" "--date=format:%Y%m%d-%H%M%S")}
distro=$(lsb_release -is 2>/dev/null || sh -c "source /etc/os-release && echo \$NAME")
distver=$(lsb_release -rs 2>/dev/null || sh -c "source /etc/os-release && echo \$VERSION_ID")
debname=wezterm-$TAG_NAME.$distro$distver
sudo dpkg -i ./$debname.deb

cd ..
rm -rf /tmp/wezterm
